sudo: required
language: c

services:
  - docker

before_install:
  - docker info
  - docker build -f Dockerfile -t cnproxy/shadowsocks-kcptun:1.0 .
  - docker build -f Dockerfile -t cnproxy/shadowsocks-kcptun .

script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push cnproxy/shadowsocks-kcptun:1.0
      docker push cnproxy/shadowsocks-kcptun
    fi
